source $HOME/.config/nvim/modules/.vimrc
source $HOME/.config/nvim/modules/colors.vim
source $HOME/.config/nvim/modules/plugins.vim
source $HOME/.config/nvim/modules/mappings.vim
source $HOME/.config/nvim/modules/fzf.vim
source $HOME/.config/nvim/modules/rg.vim
source $HOME/.config/nvim/modules/coc.vim
source $HOME/.config/nvim/modules/startify.vim
"source $HOME/.config/nvim/modules/which_key.vim
